### ISSUE TITLE
Product Management Admin Panel Layout Design Correction

### ISSUE THREAD

**Issue by tgsiva** [tgsiva/Products-Buying#1]
# Modifications

1 . Need Alignment Properly
2 . Products Images ->Multiple Image Uploads (fixed Size) going to compare Others.
3 . Products Tags should be needed on add products page
4 . Theme Breadcrumbs Need.
5 . Product weight Unit's Place holder.
6 . checkout replace to notification.
7 . Checkbox like products view Page(design).
8 . Sorting on table menu Only active only visible others are not visible
9 . Pagination should placed on the top Right corner of the table.
10 . There are 25 Products available.This comment showing on top of left corner on the table.
11 . Supplier Details in the Products view (Needed).
12 . No need price in Products view.
13 . Advanced Search -> pop Window for filtration purpose
14 . Group button to add Products in the product view Page.
15 . Primary color is our Products buying logo's green color.
16 . Responsive should check.
18 . Flexible table needed.

**Comment by manimegalatavva** [comment]
1.Add product Designed Changed.
2.Product Description in height Increased.
3.Product tag in update the Note message.
4.Buttons are alligned to the Table corner.
5.Input text box size is increasing.
6.Save button is added to the single product page.
