### ISSUE TITLE
Supplier Menu Design

### ISSUE THREAD

**Issue by tgsiva** [tgsiva/Products-Buying#3]
Design Supplier Add Page like industry buying website
Design view supplier page
Design Supplier Approval Page

**Comment by manimegalatavva** [comment]
1. Add to two sub menus in the Product buying .
2. They are add suplier,view supplier.
3. Add supplier in new Form created.
4. View supplier in linked to edit supplier page.
5. Edit supplier page created.

**Comment by manimegalatavva** [comment]
1.New sub menu Created(Approval).
2.Approval page created.
3.Add supplier page in Headings are changed.
4.Supplier Products new page Created.
5.And linked to New Supplier Products View Page created.
6.Kvs Form Designed.
7. Dash Board Added to  Kvs Page.

**Comment by manimegalatavva** [comment]
1. Supplier Order Details new page created.
2.supplier Order Details in new search page created.(Order Details new page crteated.)
3.Supplier Payment Details New page created.
4.Supplier Payment New View Page created.
5.all previous pages in table boreders changed.

**Comment by manimegalatavva** [comment]
1.Add Supplier in Jquary Form Validation Created.
2.Supplier Edit in Jquary Form Validation Created.
